language: node_js
node_js:
- '8'
branches:
  only:
  - nightly
  - master
  - sandbox
script:
- eval "$(ssh-agent -s)"
- ssh-keyscan -H 194.87.110.17 >> ~/.ssh/known_hosts
- chmod 600 $HOME/.ssh/physics
- ssh-add $HOME/.ssh/physics
- npm run build
- scp -r ./public fourtytwo@194.87.110.17:~/frontend
before_install:
- openssl aes-256-cbc -K $encrypted_512921844218_key -iv $encrypted_512921844218_iv
  -in physics.enc -out $HOME/.ssh/physics -d
